name: Testing build (on PR)

on:
    pull_request:
        branches: [ main ]
        types: [ labeled, opened, synchronize, reopened ]

jobs:
    call-testing-build-workflow:
        uses: PillowFortOrg/.github/.github/workflows/testing-build.yml@main
